import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Saladillo Vivo",
  description: "Generated by Gemini",
};

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import Script from "next/script";
import MediaPlayerWrapper from "@/components/MediaPlayerWrapper"; // Changed import


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <head>
      </head>
      <body className="bg-main-gradient">
        <MediaPlayerWrapper> {/* Changed component */}
          <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
          <Toaster />
        </MediaPlayerWrapper>
        <Script src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1" strategy="afterInteractive" />
      </body>
    </html>
  );
}
