import type { Metadata } from "next";
import "@/app/globals.css";
import dynamic from 'next/dynamic'; // Importar dynamic

export const metadata: Metadata = {
  title: "Saladillo Vivo",
  description: "Generated by Gemini",
};

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import Script from "next/script";
import { NewsProvider } from "@/context/NewsContext";

// Importar MediaPlayerWrapper dinámicamente con ssr: false
const DynamicMediaPlayerWrapper = dynamic(() => import("@/components/MediaPlayerWrapper"), { ssr: false });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <head>
      </head>
      <body className="bg-main-gradient">
        <NewsProvider>
          <DynamicMediaPlayerWrapper> {/* Usar el componente dinámico */}
            <div className="flex flex-col min-h-screen">
              <Header />
              <main className="flex-grow">{children}</main>
              <Footer />
            </div>
            <Toaster />
          </DynamicMediaPlayerWrapper>
        </NewsProvider>
        <Script src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1" strategy="afterInteractive" />
      </body>
    </html>
  );
}